server:
  port: 10010 #服务端口
spring:
  application:
    name: api-gateway #指定服务名

eureka:
  client:
    service-url: # 映射路径对应的实际url地址
      defaultZone: http://127.0.0.1:10088/eureka
    registry-fetch-interval-seconds: 5
#    fetch-registry: false # 去除自己的注册 ()
#    register-with-eureka: false  (放开后会访问报错-待定)
# 网关配置默认路由前缀（统一配默认请求前缀）
zuul:
  prefix: /api  # 添加路由前缀
  routes:
    item-service: /item/**
# 配置全局异常熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000 # 熔断超时时长：7000ms

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数（切换服务重试次数）
  MaxAutoRetries: 0 # 同一实例的重试次数（当前服务重试次数）